#### Видеокурс по теории вероятностей и математической статистике (20 ноября - 30 декабря)
Домашнее задание

*Урок 6 Взаимосвязь величин. Показатели корреляции. Корреляционный анализ. Проверка на нормальность

#### 1. Даны значения величины заработной платы заемщиков банка (zp) и значения их
поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с
помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и
среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.


In [1]:
import numpy as np
import pandas as pd

In [2]:
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110]
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]

Ковариация рассчитывается по формуле$$cov_{XY} = M[(X - M(X))(Y - M(Y))] = M(XY) - M(X)M(Y)$$

In [3]:
XY = 0
X = 0
Y = 0
n = len(zp)
for el in range(0,n):
    XY += zp[el] * ks[el]
    X += zp[el]
    Y += ks[el]

M_XY = XY / n
M_X = X / n
M_Y = Y / n

cov_XY = M_XY - M_X * M_Y
print(f'ковариация смещенная:{cov_XY}')

ковариация смещенная:9157.839999999997


In [4]:
np.cov(zp,ks,ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

Несмещённую оценку можно посчитать следующим образом:
$$\sigma_{xy} = \dfrac{1}{n - 1} \displaystyle\sum_{i = 1}^n (x_i - \overline{x}) \cdot (y_i - \overline{y})$$

In [5]:
sigma_XY_sum = 0
for el in range(0,n):
    sigma_XY_sum += (zp[el] - M_X) * (ks[el] - M_Y)
sigma_XY = sigma_XY_sum / (n - 1)
print(f'Несмещенная оценка ковариации sigma_XY: {sigma_XY}')

Несмещенная оценка ковариации sigma_XY: 10175.377777777778


In [6]:
np.cov(zp, ks, ddof=1)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

__коэффициент корреляции Пирсона__:
$$r_{XY} = \dfrac{\sigma_{XY}}{\sigma_X \cdot \sigma_Y}.$$

Здесь $\sigma_X$, $\sigma_Y$ — среднее квадратическое отклонение.

средние квадратические отклонения можнонайти из формулы расчета дисперсии

$$\sigma^2 = \dfrac{1}{m} \displaystyle\sum_{i = 1}^m \left( x_i - \overline{x} \right)^2$$

In [7]:
sigma_X_sum = 0
sigma_Y_sum = 0
for el in range(0,n):
    sigma_X_sum += (zp[el] - M_X) ** 2
    sigma_Y_sum += (ks[el] - M_Y) ** 2
sigma_X = sigma_X_sum / (n - 1)
sigma_Y = sigma_Y_sum / (n - 1)
r_XY = sigma_XY / ((sigma_X ** 0.5) * (sigma_Y ** 0.5))
print(f'Коэффициент корреляции Пирсона r_XY: {r_XY}')

Коэффициент корреляции Пирсона r_XY: 0.8874900920739162


In [8]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

###### затем с использованием функций из библиотек numpy и pandas

In [9]:
df = pd.DataFrame({"zp" : [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], 
                   "ks" : [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]})
df['zp'].corr(df['ks'])

0.8874900920739163

In [10]:
np.corrcoef(zp, ks)[0,1]

0.8874900920739163

#### 2. Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.


In [11]:
df = pd.DataFrame({'iq':[131, 125, 115, 122, 131, 115, 107, 99, 125, 111]})
# среднее квадратичное отклонение
df_std = df['iq'].std(ddof=1)
df_std

10.54566788359614

In [12]:
# Поскольку дисперсия нам неизвестна,будем использовать  t-распределение и t-статистику Стьюдента:
p=0.95
alpha = 1 - p

In [13]:
df.shape[0]

10

In [16]:
import scipy.stats as stats
#если совокупность распределена нормально
n = df.shape[0]
t1 = stats.t.ppf(alpha / 2, df = n - 1)
t2 = stats.t.ppf(1 - alpha / 2, df = n - 1)

t1, t2

(-2.2621571627409915, 2.2621571627409915)

In [17]:
#ширина доверитаельного интеравала
X_=df['iq'].mean() # выборочное среднее
interval = (X_ + t1 * df_std / np.sqrt(n), X_ + t2 * df_std / np.sqrt(n))
print(f'Доверительный интервал:{interval}')

Доверительный интервал:(110.55608365158724, 125.64391634841274)


#### 3. Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для
математического ожидания с надежностью 0.95.

In [24]:
#используем криетрий стьюдента с известной дисперсией
D = 25
sigma = 25**0.5
n = 27
X_ = 174.2
p = 0.95
alpha = 1 - p

In [25]:
t1 = stats.norm.ppf(alpha / 2)
t2 = stats.norm.ppf(1 - alpha / 2)
t1, t2

(-1.959963984540054, 1.959963984540054)

In [27]:
interval = (X_ + t1 * sigma / np.sqrt(n), X_ + t2 * sigma / np.sqrt(n))
print(f'Доверительный интервал:{interval}')

Доверительный интервал:(172.3140237765397, 176.08597622346028)
